# implementation of graph in python 


#  1) implement a graph using an adjacency matrix

In [3]:
import numpy as np
 
# set of vertices
vertices = {0, 1, 2, 3, 4, 5}
# set of edges
edges = {(0, 1), (1, 2), (0, 3), (1, 3), (3, 4), (2, 5), (4, 5), (2, 4)}

# create a NXN integer numpy array with all values initialised to zero N=V
adjacencyMatrix = np.zeros((6, 6)).astype(int)
# Represent edges in the adjacency matrix
for edge in edges:
    v1 = edge[0]
    v2 = edge[1]
    adjacencyMatrix[v1][v2] = 1
    adjacencyMatrix[v2][v1] = 1 # if v1 is connected to v2, v2 is also connected to v1
print("The set of vertices of the graph is:")
print(vertices)
print("The set of edges of the graph is:")
print(edges)
print("The adjacency matrix representing the graph is:")
print(adjacencyMatrix)

The set of vertices of the graph is:
{0, 1, 2, 3, 4, 5}
The set of edges of the graph is:
{(0, 1), (2, 4), (1, 2), (3, 4), (0, 3), (4, 5), (2, 5), (1, 3)}
The adjacency matrix representing the graph is:
[[0 1 0 1 0 0]
 [1 0 1 1 0 0]
 [0 1 0 0 1 1]
 [1 1 0 0 1 0]
 [0 0 1 1 0 1]
 [0 0 1 0 1 0]]


# 2) implement a graph using an adjacency list

In [4]:
# set of vertices
vertices = {0, 1, 2, 3, 4, 5}
# set of edges
edges = {(0, 1), (1, 2), (0, 3), (1, 3), (3, 4), (2, 5), (4, 5), (2, 4)}

# create a dictionary with vertices of graph as keys and empty lists as values

adjacencyList={}
for vertex in vertices:
    adjacencyList[vertex]=[]
    
# Represent edges in the adjacency List
for edge in edges:
    v1 = edge[0]
    v2 = edge[1]
    adjacencyList[v1].append(v2)
    adjacencyList[v2].append(v1) # if v1 is connected to v2, v2 is also connected to v1
print("The set of vertices of the graph is:")
print(vertices)
print("The set of edges of the graph is:")
print(edges)
print("The adjacency List representing the graph is:")
print(adjacencyList)

The set of vertices of the graph is:
{0, 1, 2, 3, 4, 5}
The set of edges of the graph is:
{(0, 1), (2, 4), (1, 2), (3, 4), (0, 3), (4, 5), (2, 5), (1, 3)}
The adjacency List representing the graph is:
{0: [1, 3], 1: [0, 2, 3], 2: [4, 1, 5], 3: [4, 0, 1], 4: [2, 3, 5], 5: [4, 2]}
